sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - "11.0"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
  - npm install -g firebase-tools
script:
  - npm install
  - ng build --prod
  - firebase deploy --token "$FIREBASE_TOKEN" --non-interactive